name: ad_lincs_signature

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - r-base=4.2.0

  # R packages
  - r-optparse
  - r-data.table=1.14.2
  - r-dplyr=1.1.4
  - r-tidyr=1.3.1
  - r-stringr=1.5.1
  - r-ggplot2=4.0.1
  - r-ggpubr
  - r-jsonlite=2.0.0
  - r-readxl=1.4.1
  - r-readr=2.1.5
  - r-purrr=1.0.4
  - r-abind
  - r-factoextra=1.0.7

  # Bioconductor packages
  - bioconductor-pharmacogx=3.0.2
  - bioconductor-coregx=2.0.2
  - bioconductor-cmapr=1.8.0
  - bioconductor-fgsea=1.22.0
  - bioconductor-limma=3.52.4
  - bioconductor-keggrest
  - bioconductor-biobase=2.56.0
  - bioconductor-summarizedexperiment=1.26.1
